/* eslint-disable */
// Generated by Wrangler by running `wrangler types worker-configuration.d.ts --config wrangler.jsonc --include-runtime=false` (hash: 379f464c6f8e959898e5e265166cb8ff)
interface __BaseEnv_Env {
	IMAGES: ImagesBinding;
	ASSETS: Fetcher;
	REALTIME_ORIGIN: "https://realtime.waitland.app";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "REALTIME_ORIGIN">> {}
}
