/* eslint-disable */
// Generated by Wrangler by running `wrangler types worker-configuration.d.ts --config wrangler.jsonc --include-runtime=false --strict-vars=false` (hash: 721412ae7584a8834fc3b6d73df1d104)
interface __BaseEnv_Env {
	ALLOWED_ORIGINS: string;
	SESSION_SECRET: string;
	LOBBY: DurableObjectNamespace<import("./src/index").Lobby>;
	ROOMS: DurableObjectNamespace<import("./src/index").FieldRoom>;
	PIT: DurableObjectNamespace<import("./src/index").PitCoordinator>;
	PIT_FANOUT: DurableObjectNamespace<import("./src/index").PitFanout>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "Lobby" | "FieldRoom" | "PitCoordinator" | "PitFanout";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
